---
- name: Installer BIND9
  ansible.builtin.apt:
    name: bind9
    state: present
    update_cache: true
  notify: Redémarrer bind9

- name: Configurer le fichier named.conf.options
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    mode: '0644'
  notify: Redémarrer bind9

- name: Configurer le fichier de zone pour le réseau local
  ansible.builtin.template:
    src: db.mcm.local.j2
    dest: "/etc/bind/db.mcm.local"
    mode: "0644"
  notify: Redémarrer bind9

- name: Configurer le fichier named.conf.local
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    mode: "0644"
  notify: Redémarrer bind9
