---
- name: Create ansible user
  user:
    name: ansible
    state: present
    createhome: yes
    shell: /bin/bash

- name: Add ansible user to sudo group
  user:
    name: ansible
    groups: sudo
    append: yes

- name: Allow ansible user to run sudo without password
  copy:
    dest: /etc/sudoers.d/ansible
    content: "ansible ALL=(ALL) NOPASSWD:ALL\n"
    mode: '0440'

- name: Ensure .ssh directory exists
  file:
    path: /home/ansible/.ssh
    state: directory
    owner: ansible
    group: ansible
    mode: '0700'

- name: Copy authorized_keys
  copy:
    src: /home/eboudi/.ssh/id_rsa.pub
    dest: /home/ansible/.ssh/authorized_keys
    owner: ansible
    group: ansible
    mode: '0600'