---
- name: Create user
  ansible.builtin.user:
    name: "{{ super_user }}"
    password: "{{ user_password_hash }}"
    state: present
    createhome: true
    shell: /bin/bash

- name: Add user to sudo group
  ansible.builtin.user:
    name: "{{ super_user }}"
    groups: sudo
    append: true

- name: Allow user to run sudo without password
  ansible.builtin.copy:
    dest: /etc/sudoers.d/"{{ super_user }}"
    content: '{{ super_user }} ALL=(ALL) NOPASSWD:ALL'
    mode: '0440'

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: /home/"{{ super_user }}"/.ssh
    state: directory
    owner: "{{ super_user }}"
    group: "{{ super_user }}"
    mode: '0700'

- name: Copy authorized_keys
  ansible.builtin.copy:
    src: ~/.ssh/id_rsa.pub
    dest: /home/"{{ super_user }}"/.ssh/authorized_keys
    owner: "{{ super_user }}"
    group: "{{ super_user }}"
    mode: '0600'
