---
- name: Vérifier si le répertoire NetworkManager existe
  ansible.builtin.stat:
    path: /etc/NetworkManager/conf.d
  register: nm_conf_dir

- name: Créer le répertoire NetworkManager si non existant
  ansible.builtin.file:
    path: /etc/NetworkManager/conf.d
    state: directory
    mode: '0755'
  when: not nm_conf_dir.stat.exists

- name: Modifier le fichier dns.conf
  ansible.builtin.template:
    src: dns.conf.j2
    dest: /etc/NetworkManager/conf.d/dns.conf
    mode: 'O644s'
  notify: redémarrer bind9

- name: Modifier le fichier resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: '0644'
  notify: redémarrer bind9
