---
- name: Restart wazuh-manager
  ansible.builtin.service:
    name: wazuh-manager
    state: restarted
    enabled: yes

- name: Restart filebeat
  ansible.builtin.service:
    name: filebeat
    state: restarted
    enabled: yes
